import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


export const metadata = {
  title: "Avnesh - Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
<html lang="en">
  <head>
    <meta name="theme-color" content="#000000" />
    <meta
      name="description"
      content="Web site created using create-react-app"
    />
    <title>Avnesh - Portfolio</title>
  </head>
  <body>
    <div id="root">{children}</div>
  </body>
</html>
  );
}
